apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: flask-app
      containers:
      - name: flask-app
        image: 338456725408.dkr.ecr.ap-northeast-1.amazonaws.com/flask:2022-07-06H03.11.58-975ae3d
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: AWS_DEFAULT_REGION
          value: ap-northeast-1
        - name: DYNAMODB_TABLE_NAME
          value: messages-dev
  selector:
    matchLabels:
      app: flask-app
